from utils.strings import Strings

STRINGS = {
    "ru": {
        "no_access": "У вас нет доступа к inline MCUB bot",
        "no_access_id": "ID: {sender_id}",
        "mcub_bot_title": "MCUB Bot",
        "version": "Version",
        "modules": "Modules",
        "info_description": "Info userbot",
        "command": "Команда",
        "execute": "Выполнить",
        "no_commands": "Нет зарегистрированных inline-команд",
        "form_not_found": "Форма не найдена или истекла",
        "form_id": "ID",
        "error": "Inline query error",
        "error_description": "E",
        "btn_default": "Кнопка",
        "json_parsing_error": "Ошибка парсинга JSON кнопок",
        "form_expired": "Форма не найдена",
        "traceback_invalid_id": "Неверный ID ошибки",
        "traceback_expired": "Трейсбэк истёк в кэше",
        "full_traceback": "Full Traceback",
        "critical_error": "Критическая ошибка",
        "invalid_request": "Неверный запрос",
        "no_similar_errors": "Нет похожих ошибок",
        "similar_errors": "Похожие ошибки",
        "similar_count": "count",
        "invalid_format": "Неверный формат данных",
        "error_muted": "error_type",
        "muted_for_hour": "{error_type} ({source}) заглушён на 1ч",
        "confirm_yes": "Подтверждено",
        "command_confirmed": "Команда подтверждена",
        "executing": "Выполняю",
        "confirm_no": "Отменено",
        "command_cancelled": "Команда отменена",
        "command_not_found": "Команда не найдена",
        "command_not_found_or_executed": "Команда не найдена или уже выполнена",
        "nothing_to_cancel": "Нечего отменять",
        "data_error": "Ошибка данных",
        "catalog_not_loaded": "Каталог не загружен",
        "catalog_title": "Каталог модулей",
        "page": "Стр",
        "no_description": "Описание отсутствует",
        "author": "Автор",
        "commands": "Команды",
        "use_dlm": "Используйте",
        "nav_back": "Назад",
        "nav_forward": "Вперёд",
    },
    "en": {
        "no_access": "You don't have access to inline MCUB bot",
        "no_access_id": "ID",
        "mcub_bot_title": "MCUB Bot",
        "version": "Version",
        "modules": "Modules",
        "info_description": "Info userbot",
        "command": "Command",
        "execute": "Execute",
        "no_commands": "No registered inline commands",
        "form_not_found": "Form not found or expired",
        "form_id": "ID",
        "error": "Inline query error",
        "error_description": "E",
        "btn_default": "Button",
        "json_parsing_error": "JSON buttons parsing error",
        "form_expired": "Form not found",
        "traceback_invalid_id": "Invalid error ID",
        "traceback_expired": "Traceback expired in cache",
        "full_traceback": "Full Traceback",
        "critical_error": "Critical error",
        "invalid_request": "Invalid request",
        "no_similar_errors": "No similar errors",
        "similar_errors": "Similar errors",
        "similar_count": "count",
        "invalid_format": "Invalid data format",
        "error_muted": "error_type",
        "muted_for_hour": "{error_type} ({source}) muted for 1h",
        "confirm_yes": "Confirmed",
        "command_confirmed": "Command confirmed",
        "executing": "Executing",
        "confirm_no": "Cancelled",
        "command_cancelled": "Command cancelled",
        "command_not_found": "Command not found",
        "command_not_found_or_executed": "Command not found or already executed",
        "nothing_to_cancel": "Nothing to cancel",
        "data_error": "Data error",
        "catalog_not_loaded": "Catalog not loaded",
        "catalog_title": "Module Catalog",
        "page": "Page",
        "no_description": "No description",
        "author": "Author",
        "commands": "Commands",
        "use_dlm": "Use",
        "nav_back": "Back",
        "nav_forward": "Forward",
    },
}


def get_strings(kernel) -> Strings:
    return Strings(kernel, STRINGS)
